### ISSUE TITLE
 Problems setting up fzf-sc

### ISSUE THREAD

**Issue by clfest** [madskjeldgaard/fzf-sc#10]
I am trying to set up my Raspberry Pi 400 for Supercollider. I am following madskjeldgaard for his instructions whereby Neovim can be made into an IDE for Supercollider. I’ve got scnvim installed and I’m using Lua for all my config files. I’m trying to set up fzf-sc so that I may have some indexing and that sort of stuff but I run into errors setting it up. I am very new at Lua. All my plugins take place in this file plugins.lua:

-- plugins.lua

return require('packer').startup(function()
    use 'wbthomason/packer.nvim'

local scnvim = require 'scnvim'
local map = scnvim.map
local map_expr = scnvim.map_expr
scnvim.setup {
  keymaps = {
    ['<M-e>'] = map('editor.send_line', {'i', 'n'}),
    ['<C-e>'] = {
      map('editor.send_block', {'i', 'n'}),
      map('editor.send_selection', 'x'),
    },
    ['<CR>'] = map('postwin.toggle'),
    ['<M-CR>'] = map('postwin.toggle', 'i'),
    ['<M-L>'] = map('postwin.clear', {'n', 'i'}),
    ['<C-k>'] = map('signature.show', {'n', 'i'}),
    ['<F12>'] = map('sclang.hard_stop', {'n', 'x', 'i'}),
    ['<leader>st'] = map('sclang.start'),
    ['<leader>sk'] = map('sclang.recompile'),
    ['<F1>'] = map_expr('s.boot'),
    ['<F2>'] = map_expr('s.meter'),
  },
  editor = {
    highlight = {
      color = 'IncSearch',
    },
  },
  postwin = {
    float = {
      enabled = true,
    },
  },
  documentation = {                                                                                                                                                                               
    cmd = '/usr/bin/pandoc',                                                                                                                                                             
  },
}

use { 'ibhagwan/fzf-lua',
  -- optional for icon support
  requires = { 'nvim-tree/nvim-web-devicons' }
}

-- hjh exp 2023-05-01
use {
	'madskjeldgaard/fzf-sc',
	requires = {
		'vijaymarupudi/nvim-fzf',
		'davidgranstrom/scnvim'
	}
}

scnvim.load_extension('fzf-sc')
-- end exp
end)

when I fire up Neovim I get the error message:
Error detected while processing /home/fearlessleader/.config/nvim/init.lua:
E5113: Error while calling lua chunk: …e/nvim/site/pack/packer/start/packer.nv
im/lua/packer.lua:1023: …/site/pack/packer/start/scnvim/lua/scnvim/extensions.
lua:38: [scnvim] “fzf-sc” was not found
stack traceback:
[C]: in function ‘error’
…e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:1023: in fun
ction <…e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:989>
[C]: in function ‘require’
/home/fearlessleader/.config/nvim/init.lua:13: in main chunk
Press ENTER or type command to continue

and the last line of packer.nvim.log

[ERROR Fri 05 May 2023 01:31:30 AM PDT 2.6909136865711e+15] …e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:1022: Failure running setup function: ‘…/site/pack/packer/start/scnvim/lua/scnvim/extensions.lua:38: [scnvim] “fzf-sc” was not found’

I am using Neovim v0.7.2

Any ideas where I have gone wrong?

                                Thank You For Your Attention

**Comment by madskjeldgaard** [comment]
Did you run PackerInstall afterwards? Sounds like it isnt installedSent from my iPhoneOn 8 May 2023, at 06.53, clfest ***@***.***> wrote:﻿
I am trying to set up my Raspberry Pi 400 for Supercollider. I am following madskjeldgaard for his instructions whereby Neovim can be made into an IDE for Supercollider. I’ve got scnvim installed and I’m using Lua for all my config files. I’m trying to set up fzf-sc so that I may have some indexing and that sort of stuff but I run into errors setting it up. I am very new at Lua. All my plugins take place in this file plugins.lua:
-- plugins.lua
return require('packer').startup(function()
use 'wbthomason/packer.nvim'
local scnvim = require 'scnvim'
local map = scnvim.map
local map_expr = scnvim.map_expr
scnvim.setup {
keymaps = {
[''] = map('editor.send_line', {'i', 'n'}),
[''] = {
map('editor.send_block', {'i', 'n'}),
map('editor.send_selection', 'x'),
},
[''] = map('postwin.toggle'),
[''] = map('postwin.toggle', 'i'),
[''] = map('postwin.clear', {'n', 'i'}),
[''] = map('signature.show', {'n', 'i'}),
[''] = map('sclang.hard_stop', {'n', 'x', 'i'}),
['st'] = map('sclang.start'),
['sk'] = map('sclang.recompile'),
[''] = map_expr('s.boot'),
[''] = map_expr('s.meter'),
},
editor = {
highlight = {
color = 'IncSearch',
},
},
postwin = {
float = {
enabled = true,
},
},
documentation = {
cmd = '/usr/bin/pandoc',
},
}
use { 'ibhagwan/fzf-lua',
-- optional for icon support
requires = { 'nvim-tree/nvim-web-devicons' }
}
-- hjh exp 2023-05-01
use {
'madskjeldgaard/fzf-sc',
requires = {
'vijaymarupudi/nvim-fzf',
'davidgranstrom/scnvim'
}
}
scnvim.load_extension('fzf-sc')
-- end exp
end)
when I fire up Neovim I get the error message:
Error detected while processing /home/fearlessleader/.config/nvim/init.lua:
E5113: Error while calling lua chunk: …e/nvim/site/pack/packer/start/packer.nv
im/lua/packer.lua:1023: …/site/pack/packer/start/scnvim/lua/scnvim/extensions.
lua:38: [scnvim] “fzf-sc” was not found
stack traceback:
[C]: in function ‘error’
…e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:1023: in fun
ction <…e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:989>
[C]: in function ‘require’
/home/fearlessleader/.config/nvim/init.lua:13: in main chunk
Press ENTER or type command to continue
and the last line of packer.nvim.log
[ERROR Fri 05 May 2023 01:31:30 AM PDT 2.6909136865711e+15] …e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:1022: Failure running setup function: ‘…/site/pack/packer/start/scnvim/lua/scnvim/extensions.lua:38: [scnvim] “fzf-sc” was not found’
I am using Neovim v0.7.2
Any ideas where I have gone wrong?
                            Thank You For Your Attention

**Comment by clfest** [comment]
It seems to be performing correctly now. Noobie thanks.

**Comment by madskjeldgaard** [comment]
Nice!
